# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43a3631b91c4f14305378e6980947dd1f876c5a4f8b43de1f1cab2337f555c75d2e1325c8ae81e558a0a870acbb7951b2154f6048d92eb661ed688926ea202e7

test:
  secret_key_base: 329508058345c03d10783b05ad277e8e9197e071b42431a0e13027a51108338c526a254ac1b0cff5e81e5f294b75113895995c417f05b85067b2318a9f6115d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
